name: riders
description: A new Flutter project.

version: 1.0.3+4

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.8.1
  flutter_icons: ^1.0.0+1
  shifting_tabbar: ^0.3.1
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1
  provider: ^3.2.0
  url_launcher: ^5.4.1
  flare_splash_screen: ^3.0.0
  flutter_launcher_icons: ^0.7.4
  share: ^0.6.3+3
  launch_review: ^2.0.0
  firebase_core: ^0.4.3+2
  firebase_admob: ^0.9.0+10
  admob_flutter: ^0.3.4
  connectivity: ^0.4.6+2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
      - assets/Teddy.flr
      - assets/eight.flr
      - assets/h.flr
      - assets/malayalam.png
      - assets/english.png
      - assets/signal/
      - assets/pdf/
      - assets/json/
      - assets/background/
      - assets/icon.png
      - assets/icon_foreground.png
      - assets/h_alt.flr
      - assets/hindi.png
      - assets/sarathi_logo.png
      - assets/sarathi_cover.png
      - assets/share.flr
      - assets/rating.flr
      - assets/share2.flr
      - assets/rating2.flr
      - assets/vip_user.png
      - assets/sarathi_logo_bg.png

  fonts:
  - family: Lobster     
    fonts:
    - asset: assets/fonts/Lobster-Regular.ttf
      
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/sarathi_logo.png"
  adaptive_icon_background: "assets/sarathi_logo_bg.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
